### ISSUE TITLE
Any plan to support Python 3.x?

### ISSUE THREAD

**Issue by vishal-modi** [wiremock/python-wiremock#10]
Currently, we are using Python 2.7 but soon we are going to migrate to 3.x.

Is there any plan to support Python 3.x in near future?

**Comment by platinummonkey** [comment]
Currently supported!

It currently tests in 3.4 https://github.com/platinummonkey/python-wiremock/blob/master/tox.ini#L2  Feel free to add a PR to do additional 3.x version compatibility testing. 

this lib is using `six` under the hood to provide compatibility: https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/_compat.py
