### ISSUE TITLE
Python interface for WireMock.Net ?

### ISSUE THREAD

**Issue by StefH** [wiremock/python-wiremock#11]
Is there also support for: https://github.com/WireMock-Net/WireMock.Net ?

**Comment by platinummonkey** [comment]
any wiremock compatible API layer is fine. This was targeted for the original Java implementation. But that port (that looks like you're the primary contributor too) should be able to tell you more how much different it is.

Feel free to fork this for the .NET if it is too different, or submit a PR to add additional functionality behind a config flag. 

>  but extended with more functionality.
