### ISSUE TITLE
Https howto.

### ISSUE THREAD

**Issue by tbarabanov** [wiremock/python-wiremock#12]
Could u pleas give an example of how to configure https using the client.

**Comment by platinummonkey** [comment]
The quick start example here uses https: https://wiremock.readthedocs.io/en/latest/quickstart.html#quick-start

**Comment by platinummonkey** [comment]
or are you asking for custom cert support?

**Comment by tbarabanov** [comment]
Yes, thing like this 
@Rule
public WireMockRule wireMockRule = new WireMockRule(wireMockConfig()
    .httpsPort(8443)
    .needClientAuth(true)
    .trustStorePath("/path/to/truststore.jks")
    .trustStorePassword("mostsecret"));

**Comment by platinummonkey** [comment]
🚀have fun! `v1.2.0` should hit pypi soon
