### ISSUE TITLE
Allow the port of the server to be set at initialization

### ISSUE THREAD

**Issue by OlafMeuwese** [wiremock/python-wiremock#16]
**Problem**
The server port is now always random, making it sometimes hard to set the connection url in tests, (for instance in properties) because the port number is not determined before runtime.

**Cause**
The [constructor method](https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/server/server.py#L26) now always uses the port from the `_get_free_port()` method.

**Solution**
Add parameter to the constructor method. If none is provided, fall back to the `_get_free_port()` method. This should be backwards compatible.

**Comment by OlafMeuwese** [comment]
Willing to work on this, however I wanna know if the vision on this issue is shared by the maintainers.

**Comment by platinummonkey** [comment]
@OlafMeuwese PR's welcome :)

**Comment by abhiman2387** [comment]
Is this being worked upon?

**Comment by platinummonkey** [comment]
fixed and released in 2.0.0
