### ISSUE TITLE
Templated responses are not working

### ISSUE THREAD

**Issue by mauricioalarcon** [wiremock/python-wiremock#20]
Hi there,

Thanks for doing this bridge between Python and wiremock. I was trying to do some templating responses and noticed that the code is not supported in the Python version?

Here is a snippet of code that tries to use a template, but it always returns with the template itself, but no values replaced

```
Mappings.create_mapping(Mapping(
            request=MappingRequest(
                method=HttpMethods.GET,
                url='/dynamic'
            ),
            response=MappingResponse(
                status=200,
                body="{{request.path.[0]}}",
                transformers=["response-template"]
            )
        ))
```
Then calling the endpoint `/dynamic` returns `{{request.path.[0]}}` instead of the replacement.

I debug it a little bit, and found a way to make it work by adding `"--local-response-templating"` as part of the `server.py` arguments

```
cmd = [self.java_path, "-jar", self.jar_path, "--port", str(self.port), "--local-response-templating"]
```

After that, it returns the correct replacement. Is this a know bug? enhancement? am I missing something here?

I can send you a PR with this simple change if you want to.

**Comment by platinummonkey** [comment]
released 2.1.0 with credits to you @mauricioalarcon ❤️ 
https://pypi.org/project/wiremock/2.1.0/
