### ISSUE TITLE
Time Sleep Not Long Enough

### ISSUE THREAD

**Issue by vasuarez** [wiremock/python-wiremock#22]
Starting the mock server is failing with  `Max retries exceeded with url: /__admin` due to lines 59-64
https://github.com/platinummonkey/python-wiremock/blob/f6ac860594abe3736649ee1f1887d29812e32d71/wiremock/server/server.py#L59-L64

The time.sleep on line 49 is not long enough to have wiremock set up the mock server. 
https://github.com/platinummonkey/python-wiremock/blob/f6ac860594abe3736649ee1f1887d29812e32d71/wiremock/server/server.py#L49

Happy to make a PR to increase the time to 0.75.

**Comment by platinummonkey** [comment]
you get around this by increasing the max_attempts https://github.com/platinummonkey/python-wiremock/blob/f6ac860594abe3736649ee1f1887d29812e32d71/wiremock/server/server.py#L20
