### ISSUE TITLE
Starting WireMockServer Fails at First Run

### ISSUE THREAD

**Issue by vasuarez** [wiremock/python-wiremock#23]
Hello, 

The request library is raising a `ConnectionError` that is not being caught at this [line](https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/server/server.py#L61) of code.

This error only happens during the first attempt at starting a wiremock server. Once there is a wiremock process running in the background at the same port, the error no longer occurs. Here are the steps to reproduce the error:

1. Kill all wiremock processes (command for mac)
`ps -fea | grep wirem | awk '{print $2}' | xargs kill -9`

2. Run this code in python
```python
wm = WireMockServer(port=5555, max_attempts=50000000000)
wm.start()
```

Here is the error you should see:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: /__admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10aac1350>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

Adding a try catch block for [lines 60 to 65](https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/server/server.py#L60-L65) should fix this. 

Happy to submit a PR.

**Comment by platinummonkey** [comment]
`2.1.1` released, thanks for the PR!
