### ISSUE TITLE
Starting mocktest failed

### ISSUE THREAD

**Issue by flycows01** [wiremock/python-wiremock#28]
When i start mockserver , and begin to create_mapping, a error occurred!
like this
![image](https://user-images.githubusercontent.com/25563130/88378743-2e31d500-cdd4-11ea-967e-5eb9481453af.png)
**I wonder what's going on here**

**Comment by platinummonkey** [comment]
can you provide your setup and testing code that your using?

as well as the version of wiremock installed?

**Comment by platinummonkey** [comment]
closing - stale and likely fixed by #32
