### ISSUE TITLE
can not get connection

### ISSUE THREAD

**Issue by vbpatel73** [wiremock/python-wiremock#29]
Hi, I am getting below error. what can be wrong possibilities?
`http://localhost:53144/__admin
Traceback (most recent call last):
  File "C:\Automation\AGLC\Selenium\aglc_venv\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Automation\AGLC\Selenium\aglc_venv\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Automation\AGLC\Selenium\aglc_venv\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it`

first line shows where server started. but after than i tried below code and then got error.

`Config.base_url = 'http://localhost:53144/__admin'
mapping = Mapping(
    priority=100,
    request=MappingRequest(
        method=HttpMethods.GET,
        url='/hello'
    ),
    response=MappingResponse(
        status=200,
        body='hi'
    ),
    persistent=False,
)
mapping = Mappings.create_mapping(mapping=mapping)
all_mappings = Mappings.retrieve_all_mappings()`

**Comment by platinummonkey** [comment]
are you actually running the wiremock server at that address?

**Comment by vbpatel73** [comment]
sorry for late reply. but yes

**Comment by platinummonkey** [comment]
```create_connection sock.connect(sa) ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it``` seems to indicate the wiremock server is not accepting connections locally. You might validate that this is actually responding. 

See here for launching a standalone wiremock server: http://wiremock.org/docs/running-standalone/
API Docs: http://wiremock.org/docs/api/ to do manual postman/curl validation that it's running and listening.

**Comment by vbpatel73** [comment]
sorry I am not clear yet. can you give me simple example script which i can run and then work on it pls?

**Comment by vbpatel73** [comment]
stand alone i can work easily

**Comment by platinummonkey** [comment]
So there are 2 ways to run this with testing. For the most part it's expect that you're likely running a standalone wiremock server somewhere and you're using this tool to connect to it, configure it, then run some end-to-end or integration tests against something else. See here for running a standalone server: http://wiremock.org/docs/running-standalone/

If you need to use this tool to also start a wiremock server locally to use the client this package exists: https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/server/server.py for which you can have it start up a standalone instance in another process and manage it. This just does exactly what http://wiremock.org/docs/running-standalone/ recommends with some wrapper code, but still expects you to provide the jar that you've downloaded somewhere.

I will say though that in general if you're testing code-specific logic in the same repository using like `requests` package. You're far better off using a tool like https://github.com/getsentry/responses which can be used to directly inject a response and capture without the need for actually opening a connection to a wiremock server. Choose your poison :)
