### ISSUE TITLE
Verification of request.

### ISSUE THREAD

**Issue by sp1rs** [wiremock/python-wiremock#33]
How can we verify if the request was got called during test?
similar to this: http://wiremock.org/docs/verifying/

**Comment by platinummonkey** [comment]
use the client methods to find matches or non-matches that you're expecting :)

it's trivial to add a

```python
class TestMyAPI(unittest.TestCase):
   def test_simple(self):
     # my custom verifications
     matches = client.get_requests_matching(...)
     self.assertContains(expected, matches)

```
