### ISSUE TITLE
 How to use wiremock python client to mock Rest APIs

### ISSUE THREAD

**Issue by Apolayo27** [wiremock/python-wiremock#41]
I was looking for how to implement this solution but the last documentation was in version 1.1.5 and it is very light and the documentation in wiremock.org is only for java language

**Comment by platinummonkey** [comment]
this is just a translation of the interface that Java presents in a pythonic-form

**Comment by platinummonkey** [comment]
https://wiremock.readthedocs.io/en/latest/quickstart.html

**Comment by Apolayo27** [comment]
How could I do this in python-form and and then start the server with that stub?

            MyWireMockServer.wireMockServer.stubFor(post(urlEqualTo("/ss/api1"))
                    .willReturn(aResponse()
                            .withStatus(200)
                            .withHeader("Content-Type", "application/json")
                            .withHeader("Access-Control-Allow-Origin", "*")
                            .withBodyFile("json/resp.json")));

@platinummonkey

**Comment by platinummonkey** [comment]
The quickstart has a literal example 😄  https://wiremock.readthedocs.io/en/latest/quickstart.html#quick-start

in this case a Mapping is what you're looking for. The java implementation has shortcuts like `post(` as syntactic sugar for the Mapper Object. 

A test case https://github.com/platinummonkey/python-wiremock/blob/master/wiremock/tests/resource_tests/mappings_tests/resource_tests.py#L10 though ignore the `responses.activate` and `responses.add` bits as this is mocking the wiremock server to make this work in CI

**Comment by Apolayo27** [comment]
Thank you very much for your prompt response and great project, I have used wiremock java client and I want to do the same and with your implementation it will help me a lot. I want to replicate the creation of a server with multiple stubs and then keep it started so that my frontEnd takes what my server indicates

@platinummonkey
