### ISSUE TITLE
update wiremock jar to latest version

### ISSUE THREAD

**Issue by nadir-albajari-hs** [wiremock/python-wiremock#46]
Hi please can you update the JAR so new endpoint are available?

**Comment by KjeldSchmidt** [comment]
I have added a pull request that would achieve this in here: #48

**Comment by oleg-nenashev** [comment]
Clearly we need it as a part of WireMock Python 3.0. Maybe it makes sense to actually use WireMock 3.0 beta, to be discussed with @mikeywaites

**Comment by mikeywaites** [comment]
#48 has been merged to the main branch.  We will trigger a release to pypi today to get this out.  I think anything to do with wiremock 3.0 needs to be done in isolation as it will need a lot of testing.
