### ISSUE TITLE
Define and implement a clear release process

### ISSUE THREAD

**Issue by mikeywaites** [wiremock/python-wiremock#56]
### Summary

The code base uses semver for releases which we will continue to adopt.

Have a clear release process that is documented and potentially automated will allow us to focus on releasing features quickly and safely to the community.

cc @oleg-nenashev   Might have some ideas on this process.

**Comment by oleg-nenashev** [comment]
@mikeywaites I would suggest GitHub Actions for builds & Deploy automation, keeping SemVer for versioning policy, and Automating changelogs via tools like Release Drafter similarly to https://github.com/wiremock/wiremock-testcontainers-java . Such approach would be portable between implementations and technology stacks
