### ISSUE TITLE
Please consider bumping requests version

### ISSUE THREAD

**Issue by ghost** [wiremock/python-wiremock#6]
Hello,

Unless there is a good reason to pin `requests` package to specific version (as currently is `requests==2.13.0`), please consider bumping version or changing requests package versions specifier. I imagine anything like below should work:
```
requests>=2.13.0
requests==2.*
```
Otherwise there is annoying error message in projects where some package requires more recent requests version:

```
pip install -r requirements.txt
...
wiremock 1.1.1 has requirement requests==2.13.0, but you'll have requests 2.18.4 which is incompatible.
```

Thanks!

**Comment by platinummonkey** [comment]
updated almost all requirements to compat `~=` I can make this looser if desired (ie. `>=<major version>`, if so please re-open, thanks! 👍
