### ISSUE TITLE
Link for the documentation is broken

### ISSUE THREAD

**Issue by violette** [wiremock/python-wiremock#69]
### Proposal

Hi,

The link for the documentation on https://wiremock.readthedocs.io/en/latest/ is broken.

### Reproduction steps

Click on the documentation link (https://github.com/platinummonkey/python-wiremock/overview) leads to a 404.

**Comment by oleg-nenashev** [comment]
@platinummonkey could you please grant me access to the readthedocs account?

**Comment by oleg-nenashev** [comment]
Fixed in the new docs release

**Comment by violette** [comment]
Hi, there is still a typo in the links:
![Selection_047](https://github.com/wiremock/python-wiremock/assets/10278207/679f381e-eaba-427e-a96d-1ed1a66e6025)
Thanks.
